### ISSUE TITLE
Install fails on solving constraints in Localisation.agda

### ISSUE THREAD

**Issue by cheery** [agda/cubical#658]
I followed the https://github.com/agda/cubical/blob/master/INSTALL.md#cabal-v2-install-instructions and `make` fails into this kind of an error.

```
make AGDA_EXEC=agda gen-everythings check
make[1]: Entering directory '/archive/Documents/cubical'
runhaskell ./Everythings.hs gen-except Core Foundations Codata Experiments
agda +RTS -H3G -RTS Cubical/README.agda
Checking Cubical.README (/archive/Documents/cubical/Cubical/README.agda).
 Checking Cubical.Algebra.Everything (/archive/Documents/cubical/Cubical/Algebra/Everything.agda).
  Checking Cubical.Algebra.CommAlgebra.Localisation (/archive/Documents/cubical/Cubical/Algebra/CommAlgebra/Localisation.agda).
   Checking Cubical.Algebra.CommRing.Localisation.UniversalProperty (/archive/Documents/cubical/Cubical/Algebra/CommRing/Localisation/UniversalProperty.agda).
/archive/Documents/cubical/Cubical/Algebra/CommAlgebra/Localisation.agda:23,1-68
Failed to solve the following constraints:
  Resolve instance argument _1827 : _r_1826 ∈ Aˣ
  Candidates
    _ :
      Σ (Cubical.Algebra.CommRing.Properties.Units.R A')
      (λ r' → fst φ s ·A r' ≡ 1a)
    _ :
      Σ (Cubical.Algebra.CommRing.Properties.Units.R A')
      (λ r' → fst φ s ⁻¹ ·A r' ≡ 1a)
    (stuck)
  _1827 .fst = PathToS⁻¹R.φS⊆Aˣ cond s s∈S' .fst : fst A'
    (blocked on _1827)
when scope checking the declaration
  open import Cubical.Algebra.CommRing.Localisation.UniversalProperty
/archive/Documents/cubical/Cubical/Algebra/CommAlgebra/Localisation.agda:23,1-68
Unsolved metas at the following locations:
  /archive/Documents/cubical/Cubical/Algebra/CommRing/Localisation/UniversalProperty.agda:407,24-25
  /archive/Documents/cubical/Cubical/Algebra/CommRing/Localisation/UniversalProperty.agda:407,12-25
when scope checking the declaration
  open import Cubical.Algebra.CommRing.Localisation.UniversalProperty
GNUmakefile:53: recipe for target 'check' failed
make[1]: *** [check] Error 42
make[1]: Leaving directory '/archive/Documents/cubical'
GNUmakefile:15: recipe for target 'build' failed
make: *** [build] Error 2
```

Additionally it spat out this kind of messages while compiling:
```
/archive/Documents/cubical/Cubical/Structures/Record.agda:295,5-296,78
Could not generate equivalence when splitting on indexed family,
the function will not compute on transports by a path.
  Reason: UnsupportedYet Injectivity
                           position:    0
                           type:        ℕ
                           datatype:    ℕ
                           parameters: 
                           indices:    
                           constructor: suc
when checking the definition of fwdProperty
```

agda --version shows `Agda version 2.6.3`.

Plus when I'm trying to use it, I get the following:

```
Checking tests (/home/cheery/d/nbe/stlc/tests.agda).
 Checking ren (/home/cheery/d/nbe/stlc/ren.agda).
  Checking contextual (/home/cheery/d/nbe/stlc/contextual.agda).
   Checking lists (/home/cheery/d/nbe/stlc/lists.agda).
/home/cheery/d/nbe/stlc/lists.agda:6,1-43
Failed to find source of module Cubical.Core.Everything in any of
the following locations:
  /home/cheery/d/nbe/stlc/Cubical/Core/Everything.agda
  /home/cheery/d/nbe/stlc/Cubical/Core/Everything.lagda
  /home/cheery/.cabal/store/ghc-8.8.4/Agda-2.6.3-42877c20ead6d8cef31fb8e680ba8326d8e5b4f9f5a247bc64344028883d77fc/share/lib/prim/Cubical/Core/Everything.agda
  /home/cheery/.cabal/store/ghc-8.8.4/Agda-2.6.3-42877c20ead6d8cef31fb8e680ba8326d8e5b4f9f5a247bc64344028883d77fc/share/lib/prim/Cubical/Core/Everything.lagda
when scope checking the declaration
  open import Cubical.Core.Everything public
```

Anything else I could check?

**Comment by HilpAlex** [comment]
Running make with the latest version of agda I get the same error.

**Comment by Saizan** [comment]
The library is tested against the released version of Agda, currently 2.6.2.

However I just merged a commit that should take care of the unsolved constraints error, the other stuff is warnings.

Btw, `make` is not doing anything like an installation, it's just typechecking the files.

**Comment by cheery** [comment]
Now the `make` goes through, but I still fail on the use of the library.

```
Checking syn (/home/cheery/d/nbe/stlc/syn.agda).
 Checking ren (/home/cheery/d/nbe/stlc/ren.agda).
  Checking contextual (/home/cheery/d/nbe/stlc/contextual.agda).
   Checking lists (/home/cheery/d/nbe/stlc/lists.agda).
/home/cheery/d/nbe/stlc/lists.agda:6,1-43
Failed to find source of module Cubical.Core.Everything in any of
the following locations:
  /home/cheery/d/nbe/stlc/Cubical/Core/Everything.agda
  /home/cheery/d/nbe/stlc/Cubical/Core/Everything.lagda
  /home/cheery/.cabal/store/ghc-8.8.4/Agda-2.6.3-42877c20ead6d8cef31fb8e680ba8326d8e5b4f9f5a247bc64344028883d77fc/share/lib/prim/Cubical/Core/Everything.agda
  /home/cheery/.cabal/store/ghc-8.8.4/Agda-2.6.3-42877c20ead6d8cef31fb8e680ba8326d8e5b4f9f5a247bc64344028883d77fc/share/lib/prim/Cubical/Core/Everything.lagda
when scope checking the declaration
  open import Cubical.Core.Everything public
```

Running `Ubuntu 18.04.6 LTS`. How do I add cubical into the library path somewhere? I already tried the `.agda/libraries` but that didn't seem to have effect. I either did it wrong or then v2-install doesn't use the .agda/ -directory for configuration.

**Comment by cheery** [comment]
I figured it out. I also need to add `.adga/defaults` with libraries that I need.

```
standard-library
cubical
```

Ok. This is solved. :)
